name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Linting:
    name: Linting NodeJS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Add problem matchers
        run: echo "::add-matcher::.github/problemMatchers/eslint.json"
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.21
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Run ESLint
        run: bun lint --fix=false

  Building:
    name: Building NodeJS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Add problem matchers
        run: echo "::add-matcher::.github/problemMatchers/tsc.json"
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.21
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Build code
        run: bun build
